### ISSUE TITLE
QulightUI

### ISSUE THREAD

**Issue by Hxcktivist** [xpwn3rx/QulightUI-9#1]
Hi, it seems to me that the assembly should have been done not through ShestakUI, but through ndUI, because a very similar oUF is used there, in general I would be glad if someone would cheer up oUF_Qulight. Sry for my eng)

**Comment by Warrior-** [comment]
We are at the beginning of our journey after a complete redesign of the code. Since the previous version of the code was cobbled together from all available assemblies and is already obsolete)
